openapi: 3.0.3
info:
  title: Cuttlefish API
  description: Specification for the Cuttlefish home scheduler API.
  version: 0.0.2
externalDocs:
  description: GitHub repository
  url: "https://github.com/kevinmcareavey/cuttlefish-api"
servers:
  - url: "http://localhost:8080"
  - url: "https://cuttlefish-api.bristol-xai.uk"
security:
  - bearer_auth: []
paths:
  /login:
    post:
      summary: Retrieve API token for user
      description: Retrieve API token for user (and register if necessary).
      security:
        - {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  pattern: ^[A-Za-z0-9]+$
                  example: alice
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    pattern: ^[A-Za-z0-9]+$
                    example: alice
                  token:
                    type: string
                    format: uuid
                    example: 028b6996-18be-419b-a6a2-5b14acca0418
        "400":
          description: Bad Request
  /prices:
    get:
      summary: Retrieve price data
      description: Retrieve all import and export price data for week.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Price"
        "401":
          description: Unauthorized
  /requirements:
    post:
      summary: Submit requirements
      description: Submit new requirements for schedule.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Problem"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
  /tasks/{problem}:
    get:
      summary: Retrieve optimal task schedule
      description: Retrieve an optimal task schedule for specified problem.
      parameters:
        - name: problem
          in: path
          description: UUID for problem resource
          required: true
          schema:
            type: string
            format: uuid
            example: 9964d310-669c-47b0-9e7b-5b6ae880b1c5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/SolvedProblem"
                  - $ref: "#/components/schemas/UnsolvedProblem"
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
  /survey:
    post:
      summary: Submit survey response
      description: Submit new survey response for user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {
                "energy_saving": false,
                "stem_background": false,
                "ai_experience": true,
                "tutorial_scenario": 3,
                "tutorial_setting": 2,
                "tutorial_explanations": 4,
                "ai_schedule_opinion": 5,
                "explanation_usefulness": 5,
                "real_world_helpfulness": 3,
                "understand_ai_planning": 5,
                "xai_adoption": 4,
                "ai_confidence": 2,
                "savedSchedules": ["90af67a2-1d15-4531-a286-173741b60d9e", "a95765e9-df5f-4edb-b793-6ad6d5a841da"]
                }
        required: true
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: username,api_token
  schemas:
    Price:
      type: object
      properties:
        import_price:
          type: number
          format: float
          example: 7.245
        export_price:
          type: number
          format: float
          example: 4.58
    Problem:
      type: object
      properties:
        horizon:
          type: integer
          format: int32
          example: 168
        battery:
          type: object
          properties:
            capacity:
              type: integer
              format: int32
              example: 3
            rate:
              type: integer
              format: int32
              example: 3
            initial_level:
              type: integer
              format: int32
              example: 0
            min_required_level:
              type: integer
              format: int32
              example: 0
        appliances:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
                enum: [Washer, Dryer, Dishwasher, Vehicle]
                example: Dishwasher
              duration:
                type: integer
                format: int32
                example: 1
              rate:
                type: number
                format: float
                example: 1.2
              min_required_cycles:
                type: array
                items:
                  type: object
                  properties:
                    timesteps:
                      type: array
                      items:
                        type: integer
                        format: int32
                        example: 19
                      example: [19, 20, 21, 22]
                    min_required_cycles:
                      type: integer
                      format: int32
                      example: 1
              dependencies:
                type: array
                items:
                  type: integer
                  format: int32
                  nullable: true
                  example: null
                example: [null]
    Resource:
      type: object
      properties:
        resource:
          type: string
          format: uuid
          example: 9964d310-669c-47b0-9e7b-5b6ae880b1c5
    Task:
      type: object
      properties:
        device:
          type: string
          enum: [Washer, Dryer, Dishwasher, Vehicle, Battery]
          example: Battery
        action:
          type: string
          enum: [On, Charge, Discharge]
          example: Charge
        start:
          type: integer
          format: int32
          example: 2
        duration:
          type: integer
          format: int32
          example: 3
    SolvedProblem:
      type: object
      properties:
        status:
          type: string
          enum: [Solved]
          example: Solved
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"
        cost:
          type: number
          format: float
          example: -376.15919999999994
    UnsolvedProblem:
      type: object
      properties:
        status:
          type: string
          enum: [Unsolvable, TimeExceeded, SpaceExceeded, Error]
          example: Unsolvable
